# Configuration file for the GBS-pipeline
################################################################################

# First, basic configuration and paths:
################################################################################
project-folder: "/scratch/project_2001746/Example"                                                                  # Absolute path to the project root folder
pipeline-folder: "/scratch/project_2001746/Pipeline-GBS"                                                            # Absolute path to the pipeline folder
pipeline-config: "/scratch/project_2001746/Pipeline-GBS/GBS-pipeline_config-example.yaml"                           # Absolute path to the pipeline configuration file
report-script: "/scratch/project_2001746/Pipeline-GBS/scripts/workflow-report.Rmd"                                  # Absolute path to the report scripts (THIS OPTION SHOULD BE OBSOLETE)
barcodes: "/scratch/project_2001746/Example/barcodesID.txt"                                                         # Absolute path to the barcodes file (MAKE THIS OPTIONAL)
rawsamples: "/scratch/project_2001746/Example/rawsamples"                                                           # Absolute path to the raw samples file (MAKE THIS OPTIONAL)
genome: "/scratch/project_2001746/Example/references/Vulpes_vulpes.VulVul2.2.dna.toplevel.fa"                       # Absolute path to an existing reference genome, leave empty "" if not available
genome-bwa-index: "/scratch/project_2001746/Example/references/Vulpes_vulpes.VulVul2.2.dna.toplevel.fa.bwt"         # Absolute path to the bwa index (THIS OPTION SHOULD BE OBSOLETE)
genome-star-index:  "/scratch/project_2001746/Example/references/STAR2.7.3a"                                        # Absolute path to the star index (THIS OPTION SHOULD BE OBSOLETE)
refsample: ""                                                                                                       # Id of ref sample used to build mock reference (NOT SURE, IF USED, CHECK THIS)
local-scratch: $LOCAL_SCRATCH                                                                                       # Path for fast local storage for tmp files (Here, a system variable is used. Check with your server configs)
adapter: "/scratch/project_2001746/Pipeline-GBS/adapter.fa"                                                         # Path for the adapter sequences, used by Trimmomatic (MAKE THIS OPTIONAL)

# Parameters for the GBS-SNP-CROP tools
################################################################################
enz1: "AATTC"                     # First restriction enzyme sequence
enz2: "GCATG"                     # Second restriction enzyme sequence
libname: "AllReads"               # 
libtype: "PE"                     # LIbrary type, paired-end (PE) or single-end (SE)

# Tools specific settings
################################################################################
params:
  step1:
    start: 1                      # 
    end: 1                        # 
    threads: 10                   # Number of threads used
  step2:
    tm: "trimmomatic"             #
    threads: 20                   #
    minlen: 32                    #
    iclip: "2:30:12"              #
    leading: 30                   # Hard quality cut-off 
    slwin: "8:30"                 # Sliding window trimming (windowSize:quality). Default is 4:30.
    trail: 30                     # Hard quality cut-off
  step2b:
    q: 20                         # Quality threshold - nucleotides with lower quality will be masked. Default is 10.
  step4:
    pear: "pear"                  #
    vsearch: "vsearch"            #
    threads: 20                   #
    cl: "consout"                 #
    rl: 125                       # Stitching, reads are stichted if length(R1)-19 > rl and length(R2)-5 > rl 
    pl: 32                        #
    p: 0.01                       #
    id: 0.90                      # Default: 0.93
    db: 1                         # WARNING!!!!! ADD HERE THE LENGTH OF THE SAMPLES VECTOR, THIS MUST NOT BE HARDCODED IN PRODUCTION!!!!
    min: 80                       # 
    MR: "GSC.MR"                  #      
  step5:
    bwa: "bwa"                    #
    samtools: "samtools"          #
    threads: 20                   #
    Q: 30                         #
    q: 0                          # WARNING!!! RETURN THIS BACK TO DEFAULT FOR PRODUCTION!!! ALSO, CHECK ALL OTHER SETTINGS!!!!
    f: 0                          #
    F: 2308                       #
  step5b: 
    threads: 20                   #
  step5c:
    threads: 20                   #
  step5d:
    threads: 20                   #
    q: 0                          #
    Q: 30                         #
    f: 0                          #
    F: 2308                       #
  step5e:
    threads: 20                   #
    q: 0                          #
    Q: 30                         #
    f: 0                          #
    F: 2308                       #
  step5f:
    threads: 20                   #
    q: 0                          #
    Q: 30                         #
    f: 0                          #
    F: 2308                       #
  step6:
    masterMatrix: "GSC.MasterMatrix.txt"      # Name of the master matrix
    p: "snp"                                  # Report SNP (snp) or also Indels (indel)
  step7:
    input: "GSC.MasterMatrix.txt"
    out: "GSC.GenoMatrix.txt"
    unfiltered: "GSC.GenoMatrix.unfiltered.txt"
    p: "snp"
    mnHoDepth0: 3
    mnHoDepth1: 10
    mnHetDepth: 3
    altStrength: 0.8
    mnAlleleRatio: 0.25
    mnCall: 0.75
    mnAvgDepth: 3
    mxAvgDepth: 200
  step8:
    genoMatrix: "GSC.GenoMatrix.txt"
    unfiltered: "GSC.unfiltered"
    out: "GSC"
    format: "V"
  step9:
    flanking: 25
  
# Singularity containers
singularity:
  star: "docker://fischuu/star:2.7.3a-0.1"
  gbs: "docker://fischuu/gbs:0.1"
  cutadapt: "docker://fischuu/cutadapt:2.8-0.1"
  minimap2: "docker://fischuu/minimap2:2.17-0.1"